[project]
name = "idmodels"
description = "A Python module for modeling infectious disease."
license = {text = "MIT License"}
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dynamic = ["version"]

dependencies = [
    "iddata @ git+https://github.com/reichlab/iddata",
    "lightgbm",
    "numpy",
    "pandas",
    "sarix @ git+https://github.com/reichlab/sarix@35eea2379a9790e0457b1aed41d13509e5d5056f",
    "scikit-learn",
    "tqdm",
    "timeseriesutils @ git+https://github.com/reichlab/timeseriesutils"
]

[project.optional-dependencies]
dev = [
    "coverage",
    "pre-commit",
    "pytest",
    "ruff"
]

[project.urls]
Repository = "https://github.com/reichlab/idmodels.git"

[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]

[tool.pytest.ini_options]
tmp_path_retention_policy = "none"
testpaths = [
    "tests",
]

[tool.setuptools]
packages = {find = {where = ["src"]}}

[tool.setuptools.package-data]
idmodels = ["data/*.csv", "data/*.md"]

[tool.ruff]
line-length = 120
lint.extend-select = ["I", "Q"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "double"

[tool.ruff.format]
quote-style = "double"

[tool.setuptools.dynamic]
version = {attr = "idmodels.__version__"}
